--- 
properties: &commonMeta 
    providedBy:
        $ref: "ngsi-ld.yaml#/providedBy"
    observedAt:
        $ref: "ngsi-ld.yaml#/observedAt"
    unitCode:
        $ref: "ngsi-ld.yaml#/unitCode"


App: 
  allOf: 
    - 
      $ref: "./ngsi-ld.yaml#/Common"
  description: |
      This entity contains a harmonised description of the SMACovid App.
      
      ## Data Model
      For a full description of the following attributes refer to GSMA [IoT Big Data Harmonised Data Model](https://github.com/GSMADeveloper/NGSI-LD-Entities)
  properties: 
    isOwnedBy: 
      description: "Identifies Person/Fitbit account"
      type: string
      x-ngsi: 
        model: 
          - "http://schema.org/Person"
          - "https://schema.org/Organization"
        type: Relationship
    description: 
      $ref: "./ngsi-ld.yaml#/description"
    bloodPressure: 
      description: "blood Pressure"
      format: int32
      type: integer
      x-ngsi: 
        model: "https://schema.org/Integer"
        type: Property
    oxygenSaturation: 
      description: "Oxygen Saturation"
      format: float
      type: number
      x-ngsi: 
        model: "https://schema.org/Number"
        type: Property
    temperature: 
      description: "temperature"
      format: float
      type: number
      x-ngsi: 
        model: "https://schema.org/Number"
        type: Property
        properties: *commonMeta
    floorsBelowGround: 
      description: "Number of floors below ground within the building"
      format: int32
      type: integer
      x-ngsi: 
        model: "https://schema.org/Integer"
        type: Property
    location: 
      $ref: "./ngsi-ld.yaml#/location"
    occupier: 
      description: "Link to the occupiers of the building"
      format: URL
      type: string
      x-ngsi: 
        model: "https://schema.org/URL"
        type: Relationship
    openingHours: 
      externalDocs: 
        url: "https://schema.org/openingHours"
      items: 
        properties: 
          type: 
            type: string
          values: 
            items: 
              type: string
            type: array
        type: object
      type: array
      x-ngsi: 
        model: "https://schema.org/openingHours"
        type: Property
        uri: "https://schema.org/openingHours"
    owner: 
      description: "The owner of this building"
      format: URL
      type: string
      x-ngsi: 
        model: "https://schema.org/URL"
        type: Relationship
    refMap: 
      description: "The URL holding a map of the building"
      format: URL
      type: string
      x-ngsi: 
        model: "https://schema.org/URL"
        type: Property
    source: 
      description: "A sequence of characters giving the source of the entity data."
      type: string
      x-ngsi: 
        model: 
          - "https://schema.org/Text"
          - "https://schema.org/URL"
        type: Property
  required: 
    - address
    - category
  type: object
Categories: 
  $ref: "https://fiware.github.io/tutorials.NGSI-LD/models/openstreetmap.yaml#/Categories"