--- 
components: 
  schemas: 
    Wearable: 
      allOf: 
        - 
          $ref: "https://raw.githubusercontent.com/rui-vp-fernandes/Fiware/main/wearable.yaml#/Wearable"
    Person: 
      allOf: 
        - 
          $ref: "https://raw.githubusercontent.com/rui-vp-fernandes/Fiware/main/ngsi-ld.yaml#/Common"
        - 
          $ref: "https://raw.githubusercontent.com/rui-vp-fernandes/Fiware/main/schema.org.yaml#/Person"
      properties:
        ownsAccount: 
          description: "Identifies Person/Fitbit account"
          format: URL
          type: string
          x-ngsi: 
            model: 
              - "http://schema.org/URL"
            type: Relationship
        hasApp: 
          description: "Identifies Person/Fitbit account"
          type: string
          x-ngsi: 
            model: 
              - "http://schema.org/Person"
            type: Relationship

    App:
      allOf: 
        - 
          $ref: "./app.yaml#/App"

    
info: 
  description: "Data Models used within the SMACovid-19 application"
  title: SMACovid
  version: "1.0.0"
openapi: "3.0.0"
paths: 
  /ngsi-ld/v1/entities: 
    get: 
      responses: 
        ? "200"
        : 
          content: 
            application/ld+json: 
              schema: 
                type: object
          description: OK